config/routes.rb
Rails.application.routes.draw do
	root :to => 'pages#home'

	namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
      post 'images/photo_identify' => 'images#photo_identify', as: 'photo_identify'
      get 'items' => 'items#index', as: 'items_search'
      get 'recipes' => 'items#index', as: 'recipe_search'
			

    end
  end

	devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: 'registrations'}
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :users

  resources :recipes
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><i class="fa fa-camera"></i> Recipic</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">


            <form class="navbar-form" role="search">
                <select class="js-example-data-ajax form-control" multiple="multiple" placeholder="Search Recipes">
                  <option value="0">Search Recipes</option>
              </select>
            </form>


          </ul>
          
          <% if user_signed_in? %>
            <%= link_to "Create Recipe", new_recipe_path, class:"btn btn-success btn-create-recipe", role:"button" %>
          <% end %>

          <ul class="nav navbar-nav navbar-right">
            

            <% if user_signed_in? %>
              <span class="coinages">8000</span>
              <img src="/coin.png" alt="" width="25" class="coinage">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.first_name %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Logout",  destroy_user_session_path, method: :delete  %></li>
                  <li><%= link_to "Profile", user_path(current_user) %></li>

                </ul>
              </li>
            <% else %>

              <li><%= link_to "Login", new_user_session_path %></li>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>

            <% end %>

            

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipic</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="/select2.min.css" />

    <link rel="stylesheet" type="text/css"  href="/css/style.css">
  <link rel="stylesheet" type="text/css" href="/css/nivo-lightbox/nivo-lightbox.css">
  <link rel="stylesheet" type="text/css" href="/css/nivo-lightbox/default.css">
  <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,600,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Dancing+Script:400,700" rel="stylesheet">

    <script src="/select2.full.min.js"></script>
    <script src="/site.js"></script>
  </head>

  <body>

	<%= render 'layouts/header' %>


    <%= yield %>
  </body>
</html>